### ISSUE TITLE
Comptes utilisateurs

### ISSUE THREAD

**Issue by Segolene-Albouy** [Chartes-TNAH/TNAHBox#5]
Création des fonctionnalités pour l'ajout et la gestion de comptes utilisateurs (connexion, inscription, etc.) : la création d'un compte donne lieu à une nouvelle entrée dans la base de données.

**Comment by LauryneL** [comment]
Après la validation de la pull request #14 les fonctionnalités de gestion des comptes utilisateurs ont été intégrées à Master.

Rappel des fonctionnalités : 
- Gestion de la base de données
- Création des formulaires de connexion / enregistrement
- fonctionnalités : login, logout, register
